apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-config
data:
  application.conf: |-
    search {
    index = cortex
    uri = "http://elasticsearch-master-headless.uthaya.svc.cluster.local:9200/"
    }

    responder {
    path = [
      "https://download.thehive-project.org/responders.json"
    #"/opt/cortex/Cortex-Analyzers/responders"
    ]
    fork-join-executor {
    # Min number of threads available for analysis.
    parallelism-min = 2
    # Parallelism (threads) ... ceil(available processors * factor).
    parallelism-factor = 2.0
    # Max number of threads available for analysis.
    parallelism-max = 4
    }
    }
  logback.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration debug="false">

        <conversionRule conversionWord="coloredLevel"
                        converterClass="play.api.libs.logback.ColoredLevel"/>

        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>/var/log/cortex/application.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
                <fileNamePattern>/var/log/cortex/application.%i.log.zip</fileNamePattern>
                <minIndex>1</minIndex>
                <maxIndex>10</maxIndex>
            </rollingPolicy>
            <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
                <maxFileSize>10MB</maxFileSize>
            </triggeringPolicy>
            <encoder>
                <pattern>%date [%level] from %logger in %thread - %message%n%xException</pattern>
            </encoder>
        </appender>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%coloredLevel %logger{15} - %message%n%xException{10}
                </pattern>
            </encoder>
        </appender>

        <appender name="ASYNCFILE" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="FILE"/>
        </appender>

        <appender name="ASYNCSTDOUT" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="STDOUT"/>
        </appender>

        <logger name="play" level="INFO"/>
        <logger name="application" level="INFO"/>

        <logger name="com.gargoylesoftware.htmlunit.javascript" level="OFF"/>

        <root level="INFO">
            <appender-ref ref="ASYNCFILE"/>
            <appender-ref ref="ASYNCSTDOUT"/>
        </root>

    </configuration>

