---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: uthaya
  name: job-runner
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "watch"]