apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master-headless
  namespace: uthaya
  labels:
    app: elasticsearch-master
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: elasticsearch-master
  ports:
   - port: 9200
     name: rest
   - port: 9300
     name: inter-node
  type: ClusterIP

  