apiVersion: v1
kind: PersistentVolume
metadata:
  name: yadayada
  namespace: uthaya
  labels:
    type: local
spec:
  storageClassName: yadayada
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv/elasticsearch/esdata"
