apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: uthaya
  labels:
    app: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: uthaya
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: uthaya
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-master-0.elasticsearch-master-headless.uthaya.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SED_DISABLE
            value: "true"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_CONF
            value: "containers.conf"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /home/uthayasurian/Downloads/nginx/access_log2
          name: mydir
        - mountPath: /home/uthayasurian/Downloads/nginx/access_log2/data.log
          name: myfile
          readOnly: true
        - name: config
          mountPath: /fluentd/etc/containers.conf
          subPath: containers.conf
      terminationGracePeriodSeconds: 30
      volumes:
       - name: mydir
         hostPath:
      # Ensure the file directory is created.
           path: /home/uthayasurian/Downloads/nginx/access_log2
           type: DirectoryOrCreate
       - name: myfile
         hostPath:
           path: /home/uthayasurian/Downloads/nginx/access_log2/data.log
           type: File
       - name: config 
         configMap:
           defaultMode: 420
           name: fluentd-fluentd-config
        