---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: uthaya
  name: kibana-config
  labels:
    app: kibana
data:
  kibana.yml: |
    ---
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: http://elasticsearch:9200