apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-rule
  namespace: kube-elastalert
  labels:
    k8s-app: elastalert
data:
  rammstein.yaml: |-
    es_host: elasticsearch-master-headless.uthaya.svc.cluster.local
    es_port: 9200
    name: Example rule
    type: any
    index: logstash-20210917
    num_events: 1
    timeframe:
        days: 40
    filter:
    - query:
         query_string:
            query: "method: POST"
    alert:
    - telegram
    
    alert_text: "from elastalert - {0}, {1}, {2}"
    alert_text_args: ["type", "ip", "timestamp"]
    alert_text_type: alert_text_only

    telegram_bot_token: 5516854125:AAFqWrOCEKmZa9LiN-ZaL1tBsUERlMwYkzg

    telegram_room_id: "528054255"



